### ISSUE TITLE
Example build fails

### ISSUE THREAD

**Issue by benjbuch** [haddocking/3D-DART#1]
Following the instructions in the Readme, the example build fails at stage 4/5:

```
--> Instantiate plugin: NABendAnalyze
--> Create job directory for plugin: jobnr4-NABendAnalyze
--> Performing Global nucleic acid bend angle analysis
    * ERROR: No valid input found: '.par'
Traceback (most recent call last):
  File "./RunDART.py", line 95, in <module>
    FrameWork.PluginExecutor(opt_dict=opt_dict, DARTdir=base)
  File "../../Executables/3D-DART/system/FrameWork.py", line 34, in __init__
    self.PluginExecutor()
  File "../../Executables/3D-DART/system/FrameWork.py", line 277, in PluginExecutor
    outputlist = self._Executor(plugin, mainxml, step)
  File "../../Executables/3D-DART/system/FrameWork.py", line 118, in _Executor
    PluginCore(paramdict,filelist)
  File "../../Executables/3D-DART/plugins/NABendAnalyze.py", line 94, in PluginCore
    raise e
KeyError: '.par'
```

**Comment by brianjimenez** [comment]
Runs without any problem in a fresh instance following the install instructions. What is the content of your software folder? It should look like something similar to this:

```
(venv) {bjimenez@abiko}->[~/workspaces/haddocking/3D-DART/venv/3D-DART/software/X3DNA-mac]: ls */
BASEPARS/:
ATOMIC           Atomic_G.pdb     Atomic_U.pdb     Block_BP.alc     Pxyz.dat         RNA_BASES        col_mname.dat    misc_3dna.par    ps_image.par     trans_pep.alc
Atomic_A.pdb     Atomic_P.pdb     Atomic_i.pdb     Block_R.alc      PxyzH.dat        baselist.dat     fig_image.par    my_header.r3d    raster3d.par     trans_pep.pdb
Atomic_C.pdb     Atomic_T.pdb     BLOCK            Block_Y.alc      README           col_chain.dat    help3dna.dat     ndb_raster3d.par rotz90

FIBER/:
Data   Str02  Str05  Str08  Str11  Str14  Str17  Str20  Str23  Str26  Str29  Str32  Str35  Str38  Str41  Str44  Str47  Str50  Str53
README Str03  Str06  Str09  Str12  Str15  Str18  Str21  Str24  Str27  Str30  Str33  Str36  Str39  Str42  Str45  Str48  Str51  Str54
Str01  Str04  Str07  Str10  Str13  Str16  Str19  Str22  Str25  Str28  Str31  Str34  Str37  Str40  Str43  Str46  Str49  Str52  Str55

bin/:
EnergyPDNA.exe anyhelix       cehs           dcmnfile       fiber          get_part       nmr_ensemble   pdb2img        regular_dna    std_base
alc2img        block_atom     comb_str       del_ms         find_pair      manalyze       nmr_strs       r3d_atom       rotate_mol     step_hel
analyze        blocview       cp_std         ex_str         frame_mol      mstack2img     o1p_o2p        rebuild        stack2img
```

**Comment by benjbuch** [comment]
Ah, I see. Apparently, my directory only contained a file `architecture24.txt`. From the instructions, I see that I'm supposed to download the content from http://x3dna.org. Would you mind to be a bit more specific either where to find these files or which files are required? This would be helpful to newcomers, I guess. :)

**Comment by brianjimenez** [comment]
That is a very legit point, thanks for your feedback @benjbuch . I will update the documentation asap.

**Comment by brianjimenez** [comment]
Addressed in c94ab30f8d96ab1232d55ed136bc8299dcaa5112

**Comment by benjbuch** [comment]
Thanks for updating the instructions. I have meanwhile progressed to the X3DNA download area. There are different releases of 3DNA:

v2.4 and v2.0 don't embed the "BASEPARS" folder any longer and the capitalization/spelling of some files has changed apparently.

v1.5 is closest to the folder/file hierarchy you posted: 

```
BASEPARS	Examples	FIBER		bin

/bin     
alc2img		comb_str	find_pair	nmr_strs	rotate_mol
analyze		cp_std		frame_mol	o1p_o2p		stack2img
anyhelix	dcmnfile	get_part	pdb2img		std_base
block_atom	del_ms		manalyze	r3d_atom	step_hel
blocview	ex_str		mstack2img	rebuild
cehs		fiber		nmr_ensemble	regular_dna

/BASEPARS 
ATOMIC			Block_R.alc		help3dna.dat
Atomic_A.pdb		Block_Y.alc		misc_3dna.par
Atomic_C.pdb		Pxyz.dat		my_header.r3d
Atomic_G.pdb		PxyzH.dat		ndb_raster3d.par
Atomic_I.pdb		README			ps_image.par
Atomic_P.pdb		RNA_BASES		raster3d.par
Atomic_T.pdb		baselist.dat		rotz90
Atomic_U.pdb		col_chain.dat		trans_pep.alc
BLOCK			col_mname.dat		trans_pep.pdb
Block_BP.alc		fig_image.par

/FIBER   
Data	Str05	Str11	Str17	Str23	Str29	Str35	Str41	Str47	Str53
README	Str06	Str12	Str18	Str24	Str30	Str36	Str42	Str48	Str54
Str01	Str07	Str13	Str19	Str25	Str31	Str37	Str43	Str49	Str55
Str02	Str08	Str14	Str20	Str26	Str32	Str38	Str44	Str50
Str03	Str09	Str15	Str21	Str27	Str33	Str39	Str45	Str51
Str04	Str10	Str16	Str22	Str28	Str34	Str40	Str46	Str52
```

I have tried to run with v1.5, but it might be outdated since on macOS Catalina, I get `X3DNA-mac/bin/analyze: Bad CPU type in executable`.

**Comment by benjbuch** [comment]
Okay, so 

- running with the `bin` folder of v2.4 instead of v1.5,
- including the `config` folder of v2.4, else
- having the folder/files of v1.5 works.

Also, one needs to allow the execution of all unverified developers (the new macOS is sometimes a bit annoying) in System Preferences.

The only thing that is missing now is `EnergyPDNA.exe`:

```
--> Calculating base-pair and base-pair step deformation energy for the file: ./3D-DART/NAensemblebuild/jobnr3-X3DNAanalyze/struct_1_fixed.out
sh: EnergyPDNA.exe: command not found
sh: EnergyPDNA.exe: command not found
--> Calculating base-pair and base-pair step deformation energy for the file: ./3D-DART/NAensemblebuild/jobnr3-X3DNAanalyze/struct_5_fixed.out
sh: EnergyPDNA.exe: command not found
sh: EnergyPDNA.exe: command not found
--> Calculating base-pair and base-pair step deformation energy for the file: ./3D-DART/NAensemblebuild/jobnr3-X3DNAanalyze/struct_3_fixed.out
sh: EnergyPDNA.exe: command not found
sh: EnergyPDNA.exe: command not found
--> Calculating base-pair and base-pair step deformation energy for the file: ./3D-DART/NAensemblebuild/jobnr3-X3DNAanalyze/struct_4_fixed.out
sh: EnergyPDNA.exe: command not found
sh: EnergyPDNA.exe: command not found
--> Calculating base-pair and base-pair step deformation energy for the file: ./3D-DART/NAensemblebuild/jobnr3-X3DNAanalyze/struct_2_fixed.out
sh: EnergyPDNA.exe: command not found
sh: EnergyPDNA.exe: command not found
--> Performing multistructure analysis
    * Performing multistructure analysis on 5 parameter files
Traceback (most recent call last):
  File "./RunDART.py", line 95, in <module>
    FrameWork.PluginExecutor(opt_dict=opt_dict, DARTdir=base)
  File "./3D-DART/system/FrameWork.py", line 34, in __init__
    self.PluginExecutor()
  File "./3D-DART/system/FrameWork.py", line 277, in PluginExecutor
    outputlist = self._Executor(plugin, mainxml, step)
  File "./3D-DART/system/FrameWork.py", line 118, in _Executor
    PluginCore(paramdict,filelist)
  File "./3D-DART/plugins/X3DNAanalyze.py", line 111, in PluginCore
    multiout.ReadOutfiles()
  File "./3D-DART/plugins/X3DNAanalyze.py", line 816, in ReadOutfiles
    self._SortTable(tablein=tablelines,tableout=self.bpstep,infile=files)
  File "./3D-DART/plugins/X3DNAanalyze.py", line 402, in _SortTable
    for n in range(len(tablein[0])):
IndexError: list index out of range
```

**Comment by brianjimenez** [comment]
Nice hack! What about compiling `EnergyPDN.exe` straight from source code? https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjhvt39p5rpAhUC3xoKHTyCD1cQFjAAegQIARAB&url=http%3A%2F%2Fforum.x3dna.org%2Fusers-contributions%2Fdeformation-energy-calculation-program%2F%3Faction%3Ddlattach%3Battach%3D121&usg=AOvVaw15x7xDiXK6nwI4rNmqyO2F

**Comment by benjbuch** [comment]
Link for header: http://forum.x3dna.org/users-contributions/deformation-energy-calculation-program/?action=dlattach;attach=122

Compilation with gcc fails unfortunately: `ld: symbol(s) not found for architecture x86_64`.

**Comment by brianjimenez** [comment]
Compiles fine for me with both `EnergyPDNA.c` and `EnergyParams.h` in the same folder:

```
$ g++ -Wall -O3 EnergyPDNA.c -o EnergyPDNA.exe
$ ./EnergyPDNA.exe 

Parts of this program are:

	Olson WK, Gorin AA, Lu XJ, Hock LM, Zhurkin VB.
	  DNA sequence-dependent deformability
	  deduced from protein-DNA crystal complexes.
	  Proc Natl Acad Sci U S A. 1998 Sep 15;95(19):11163-8.

	Lankas F, Sponer J, Langowski J, Cheatham TE 3rd.
	  DNA deformability at the base pair level.
	  J Am Chem Soc. 2004 Apr 7;126(13):4124-5.

Usage:
	./EnergyPDNA.exe [switches] 3DNA.out
	[switches] are:
	 -s for step energy calcs (default).
	 -b for base energy calcs
```

**Comment by benjbuch** [comment]
I can confirm this builds with `g++`; I mistakenly assumed to use `gcc` and I'm not so familiar with building.

Now executing `3D-DART % ./RunDART.py -w NAensemblebuild -f example/struct_*.pdb` proceeds to the state of multistructure analysis, but the error is a bit cryptic. (I'm very sorry to keep bothering you.)

```
--> Performing multistructure analysis
    * Performing multistructure analysis on 5 parameter files
Traceback (most recent call last):
  File "./RunDART.py", line 95, in <module>
    FrameWork.PluginExecutor(opt_dict=opt_dict, DARTdir=base)
  File "3D-DART/system/FrameWork.py", line 34, in __init__
    self.PluginExecutor()
  File "3D-DART/system/FrameWork.py", line 277, in PluginExecutor
    outputlist = self._Executor(plugin, mainxml, step)
  File "3D-DART/system/FrameWork.py", line 118, in _Executor
    PluginCore(paramdict,filelist)
  File "3D-DART/plugins/X3DNAanalyze.py", line 111, in PluginCore
    multiout.ReadOutfiles()
  File "3D-DART/plugins/X3DNAanalyze.py", line 816, in ReadOutfiles
    self._SortTable(tablein=tablelines,tableout=self.bpstep,infile=files)
  File "3D-DART/plugins/X3DNAanalyze.py", line 402, in _SortTable
    for n in range(len(tablein[0])):
IndexError: list index out of range
```

Maybe, I'm still missing some files:

```
--> Starting PDBeditor
    * Printing fixed pdb file as: struct_2_fixed.pdb
    * Printing fixed pdb file as: struct_3_fixed.pdb
    * Printing fixed pdb file as: struct_1_fixed.pdb
    * Printing fixed pdb file as: struct_4_fixed.pdb
    * Printing fixed pdb file as: struct_5_fixed.pdb
    * WARNING: file: struct_2.pdb is not present in the output
    * WARNING: file: struct_3.pdb is not present in the output
    * WARNING: file: struct_1.pdb is not present in the output
    * WARNING: file: struct_4.pdb is not present in the output
    * WARNING: file: struct_5.pdb is not present in the output
```

**Comment by brianjimenez** [comment]
No worries at all @benjbuch . This is an old project, kind of archeological adventure ;-)

It seems X3DNA is not properly setup or not working as expected by 3D-DART, which the most probable reason is X3DNA version is different than the one I've inherited. I don't have the source code of any of the binary and no way to find any version of the software.

Is it possible for you to use version 1.5 inside a docker container, for example? My guess is that version should work with 3D-DART.
